const escapeHtml = (value: unknown): string =>
  String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");

export const renderHome = (headers: (extra?: HeadersInit) => Headers): Response =>
  new Response(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#ffffff">
<title>Zalagren</title>
<style>
:root{color-scheme:light;--ink:#0b1f3a;--muted:#5f6f83;--green:#14833b;--orange:#c66b22;--line:#dfe5ec;--surface:#fff;--surface-2:#f5f7fa;--radius-lg:24px;--radius-md:18px;--shadow:0 10px 30px rgba(11,31,58,.07);font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text","SF Pro Display","Segoe UI",sans-serif}
*{box-sizing:border-box}html{background:#fff}body{margin:0;background:#fff;color:var(--ink);min-height:100vh;-webkit-font-smoothing:antialiased}button,input{font:inherit}button{cursor:pointer}
.shell{width:min(100% - 32px,920px);margin:0 auto;padding:14px 0 48px}.topbar{position:sticky;top:12px;z-index:10;display:flex;align-items:center;justify-content:space-between;min-height:52px;padding:10px 14px;border:1px solid var(--line);border-radius:18px;background:rgba(255,255,255,.94);box-shadow:0 6px 24px rgba(11,31,58,.06);backdrop-filter:saturate(180%) blur(18px)}
.brand{font-size:18px;line-height:24px;font-weight:750;color:var(--green)}.menu{width:40px;height:40px;display:grid;place-items:center;border:0;background:transparent;color:var(--ink);font-size:20px;letter-spacing:3px;border-radius:12px}
.menu:focus-visible,.action:focus-visible,.card:focus-visible,input:focus-visible{outline:3px solid rgba(11,31,58,.25);outline-offset:2px}.page{padding:28px 0}.kicker{font-size:12px;line-height:16px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:var(--orange)}
.title{font-size:clamp(30px,7vw,44px);line-height:1.08;letter-spacing:-.025em;font-weight:760;margin:8px 0 10px;max-width:620px}.lede{font-size:16px;line-height:24px;color:var(--muted);max-width:640px;margin:0}
.auth-card,.section-card{margin-top:22px;padding:20px;border:1px solid var(--line);border-radius:var(--radius-lg);background:var(--surface);box-shadow:var(--shadow)}.auth-card{max-width:480px}
.label{display:block;font-size:14px;line-height:20px;font-weight:650;margin:14px 0 6px}input{width:100%;min-height:46px;padding:11px 13px;border:1px solid #cbd5e1;border-radius:13px;background:#fff;color:var(--ink)}input::placeholder{color:#7a8798}
.actions{display:flex;gap:10px;margin-top:16px}.action{min-height:44px;padding:10px 16px;border:0;border-radius:13px;font-weight:700}.primary{background:var(--ink);color:#fff}.secondary{background:var(--surface-2);color:var(--ink);border:1px solid var(--line)}.error{min-height:20px;margin-top:10px;color:#a33b2b;font-size:13px;line-height:19px}.hidden{display:none!important}
.home-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.identity-meta{margin-top:5px;font-size:14px;line-height:21px;color:var(--muted);overflow-wrap:anywhere}
.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:22px}.card{min-height:132px;padding:17px;text-align:left;border:1px solid var(--line);border-radius:18px;background:#fff;box-shadow:0 5px 18px rgba(11,31,58,.045);transition:transform .16s ease,border-color .16s ease}.card:hover{transform:translateY(-1px);border-color:#b9c6d5}
.card-mark{font-size:12px;line-height:16px;color:var(--orange);font-weight:700;margin-bottom:12px}.card-title{font-size:16px;line-height:21px;font-weight:720;margin-bottom:6px}.card-copy{font-size:13px;line-height:19px;color:var(--muted)}
.view{display:none;margin-top:12px;padding:18px;border:1px solid var(--line);border-radius:18px;background:#fff}.view.active{display:block}.view h2{font-size:20px;line-height:26px;letter-spacing:-.01em;margin:0 0 5px}.view-sub{font-size:13px;line-height:19px;color:var(--muted)}
.row{padding:13px 0;border-top:1px solid #edf1f5}.row:first-child{border-top:0}.row-title{font-size:14px;line-height:20px;font-weight:680}.row-meta{font-size:13px;line-height:19px;color:var(--muted);margin-top:3px}.pill{display:inline-flex;align-items:center;min-height:24px;padding:3px 8px;border-radius:999px;background:#eef3f8;color:var(--ink);font-size:11px;line-height:16px;font-weight:650;margin-left:5px}
.status{margin-top:12px;padding:14px 15px;border-radius:16px;background:var(--surface-2);border:1px solid var(--line);font-size:13px;line-height:19px;color:var(--muted)}.status strong{color:var(--ink)}.footer-actions{margin-top:16px}
@media(max-width:640px){.shell{width:min(100% - 24px,640px);padding-top:8px}.topbar{top:8px}.page{padding:22px 0}.grid{grid-template-columns:1fr}.card{min-height:108px}.actions{flex-direction:column}.action{width:100%}}
@media(min-width:641px){.auth-card{padding:22px}.page{padding-top:34px}}@media(prefers-reduced-motion:reduce){.card{transition:none}.card:hover{transform:none}}
</style>
</head>
<body>
<main class="shell">
<header class="topbar"><div class="brand">Zalagren</div><button class="menu" id="menu" type="button" aria-label="More options">•••</button></header>
<section class="page" id="auth"><div class="kicker">Intelligent Living Infrastructure</div><h1 class="title">One identity. Connected possibilities.</h1><p class="lede">Enter Zalagren through a real participant identity. Authentication stays at the production provider boundary; participant authority stays in BeatCore.</p>
<form class="auth-card" id="authForm"><div id="formTitle" class="card-title">Create your identity</div><label class="label" for="name">Name</label><input id="name" autocomplete="name" placeholder="Your name"><label class="label" for="email">Email</label><input id="email" autocomplete="email" inputmode="email" type="email" placeholder="you@example.com"><label class="label" for="password">Password</label><input id="password" autocomplete="current-password" type="password" placeholder="Password (8+ characters)"><div class="actions"><button id="submit" class="action primary" type="submit">Create account</button><button id="mode" class="action secondary" type="button">Sign in instead</button></div><div id="error" class="error" role="alert" aria-live="polite"></div></form></section>
<section class="page hidden" id="home"><div class="home-head"><div><div class="kicker">Participant home</div><h1 id="welcome" class="title">Welcome.</h1><div id="identity" class="identity-meta"></div></div></div>
<div class="grid"><button class="card" data-view="identityView" type="button"><div class="card-mark">FOUNDATION</div><div class="card-title">Identity</div><div class="card-copy">Persistent participant identity, account, and session state.</div></button><button class="card" data-view="communityView" type="button"><div class="card-mark">PARTICIPATION</div><div class="card-title">Communities</div><div class="card-copy">Real communities connected to your current participation context.</div></button><button class="card" data-view="serviceView" type="button"><div class="card-mark">CAPABILITIES</div><div class="card-title">Services</div><div class="card-copy">Registered services and their declared capabilities.</div></button><button class="card" data-view="genesisView" type="button"><div class="card-mark">INTELLIGENCE</div><div class="card-title">GENESIS</div><div class="card-copy">Proposal-only intelligence. It never becomes authority.</div></button></div>
<section id="identityView" class="view"><h2>Identity</h2><div class="view-sub">Canonical participant foundation</div><div id="identityBody"></div></section><section id="communityView" class="view"><h2>Communities</h2><div class="view-sub">Current ecosystem participation</div><div id="communityBody"></div></section><section id="serviceView" class="view"><h2>Services</h2><div class="view-sub">Declared capabilities, not assumed authority</div><div id="serviceBody"></div></section><section id="genesisView" class="view"><h2>GENESIS</h2><div class="view-sub">Intelligence proposes; authorized participants decide</div><div id="genesisBody"></div></section>
<div class="status"><strong>Session:</strong> authenticated through the production identity boundary.</div><div class="footer-actions"><button id="signout" class="action secondary" type="button">Sign out</button></div></section>
</main>
<script>
let signup=true;const $=id=>document.getElementById(id);const setError=message=>{ $("error").textContent=message||"";};
function mode(){ $("formTitle").textContent=signup?"Create your identity":"Welcome back";$("submit").textContent=signup?"Create account":"Sign in";$("mode").textContent=signup?"Sign in instead":"Create an account";$("name").classList.toggle("hidden",!signup);$("password").autocomplete=signup?"new-password":"current-password";$("password").placeholder=signup?"Password (8+ characters)":"Password";}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));const view=$(id);if(view){view.classList.add("active");view.scrollIntoView({behavior:"smooth",block:"nearest"});}}
function showHome(d){$("auth").classList.add("hidden");$("home").classList.remove("hidden");$("welcome").textContent="Welcome, "+(d?.identity?.name||"participant")+".";$("identity").textContent=(d?.identity?.email||"")+" · Participant "+(d?.participant?.participantId||"unavailable");$("identityBody").innerHTML="<div class='row'><div class='row-title'>Participant</div><div class='row-meta'></div></div><div class='row'><div class='row-title'>Identity provider</div><div class='row-meta'></div></div><div class='row'><div class='row-title'>Account</div><div class='row-meta'></div></div>";const rows=$("identityBody").querySelectorAll(".row-meta");rows[0].textContent=d?.participant?.participantId||"unavailable";rows[1].textContent=d?.identity?.provider||"neon-auth";rows[2].textContent=d?.participant?.accountId||"ready";loadViews();}
async function loadViews(){try{const responses=await Promise.all([fetch("/api/home/communities"),fetch("/api/home/services"),fetch("/api/home/foundation")]);const [communities,services,foundation]=await Promise.all(responses.map(r=>r.json()));if(responses.some(r=>!r.ok))throw new Error("HOME_DATA_UNAVAILABLE");$("communityBody").innerHTML=communities.items?.length?communities.items.map(x=>"<div class='row'><div class='row-title'></div><div class='row-meta'></div></div>").join(""):"<div class='row'><div class='row-title'>No communities connected yet.</div><div class='row-meta'>This is a real empty state; no participation has been invented.</div></div>";communities.items?.forEach((x,i)=>{const row=$("communityBody").children[i];row.querySelector(".row-title").textContent=x.name||"";row.querySelector(".row-meta").textContent=(x.type||"")+" · "+(x.location||"")+" · "+(x.verification||"");});$("serviceBody").innerHTML=services.items?.length?services.items.map(x=>"<div class='row'><div class='row-title'></div><div class='row-meta'></div></div>").join(""):"<div class='row'><div class='row-title'>No services are registered yet.</div><div class='row-meta'>Zalagren will not pretend a provider is connected.</div></div>";services.items?.forEach((x,i)=>{const row=$("serviceBody").children[i];row.querySelector(".row-title").textContent=x.name||"";row.querySelector(".row-meta").textContent=(x.domain||"")+" · "+(x.status||"")+" · Capabilities: "+((x.capabilities||[]).map(c=>c.name).join(", ")||"none");});const f=foundation.foundation||{};$("genesisBody").innerHTML="<div class='row'><div class='row-title'>Proposal-only intelligence</div><div class='row-meta'>GENESIS cannot authorize or execute actions.</div></div><div class='row'><div class='row-title'>Live foundation</div><div class='row-meta'></div></div>";$("genesisBody").lastElementChild.querySelector(".row-meta").textContent="Participants: "+(f.participants??"not exposed")+" · Actions: "+(f.actions??"not exposed")+" · Events: "+(f.events??"not exposed");}catch{["communityBody","serviceBody","genesisBody"].forEach(id=>$(id).innerHTML="<div class='row'><div class='row-title'>Live data is unavailable.</div><div class='row-meta'>The interface is preserving a truthful error state.</div></div>");}}
document.querySelectorAll(".card").forEach(card=>card.addEventListener("click",()=>showView(card.dataset.view)));$("mode").onclick=()=>{signup=!signup;setError("");mode();};$("authForm").onsubmit=async event=>{event.preventDefault();setError("");const body={email:$("email").value.trim(),password:$("password").value};if(signup)body.name=$("name").value.trim();if(!body.email||!body.password||(signup&&!body.name)){setError("Complete the required fields.");return;}const r=await fetch(signup?"/api/auth/sign-up/email":"/api/auth/sign-in/email",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||"Authentication failed.");return;}showHome(d.canonical?{identity:d.user,participant:d.canonical}:await(await fetch("/api/me")).json());};$("signout").onclick=async()=>{await fetch("/api/auth/sign-out",{method:"POST"});location.reload();};async function check(){const r=await fetch("/api/me");if(r.ok)showHome(await r.json());}mode();check();
</script>
</body></html>`,{headers:headers({"content-type":"text/html; charset=utf-8"})});
